projectTitle = "Hydra"
modId = "hydra"
modVersion = "0.8.0"
group = "com.theendercore"
githubRepo = "theendercore/Hydra"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = ">=1.21.11"
minecraftVersion = "1.21.11"
fabricLoaderVersion = "0.19.2"
fabricApiVersion = "0.141.3+1.21.11"
fabricLangKotlinVersion = "1.13.6+kotlin.2.2.20"
license = "MIT"
modules = [ ]
modDescription = "A Twitch Integrations mod to bring your chat into Minecraft and more!"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.11"