[versions]
kotlin = "2.2.20"
fabric-loom = "1.15-SNAPSHOT"
iridium = "3.5.0"
# Dependencies
fzzy-config = "0.7.6+1.21.11"
cloth-config = "21.11.153"
twitch4j = "1.25.0+1.11.0"
# QoL
modmenu = "17.0.0"
#emi = "1.1.22+1.21.1"
# Testing
creative-works = "0.5.1+1.21.11"

[libraries]
# Dependencies
fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy-config" }
cloth-config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }
twitch4j = { module = "com.github.twitch4j:twitch4j-fabric", version.ref = "twitch4j" }
# QoL
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
#emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
# Testing
creative-works = { module = "org.teamvoided:creative_works", version.ref = "creative-works" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
